
import { InventoryItem, VehicleInventory } from './types';

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: '1-02-001-0007', name: 'สายอลูมิเนียมเปลือย ขนาด 185 ต.มม.', category: 'สายไฟ', quantity: 100, unit: 'เมตร', minThreshold: 50 },
  { id: '1-02-002-0002', name: 'สายอลูมิเนียมแกนเหล็ก ขนาด 50 ต.มม.', category: 'สายไฟ', quantity: 100, unit: 'เมตร', minThreshold: 50 },
  { id: '1-02-005-0004', name: 'สายเคเบิลอากาศอลูมิเนียม ขนาด 185 ต.มม. ระบบ 22เควี', category: 'สายไฟ', quantity: 100, unit: 'เมตร', minThreshold: 50 },
  { id: '1-02-020-0003', name: 'COVERED TIE WIRE.AL.4.0 MM.', category: 'สายไฟ', quantity: 100, unit: 'เมตร', minThreshold: 50 },
  { id: '1-02-026-0205', name: 'พรีฟอร์มเดดเอ็นด์ ส่าหรับสาย SAC ขนาด 185 ต.มม. 22 เควี (รหัสใหม่)', category: 'อุปกรณ์ยึดต่อ', quantity: 3, unit: 'ชุด', minThreshold: 2 },
  { id: '1-02-030-0102', name: 'พีจี. คอนเนคเตอร์สลักคู่ ส่าหรับสาย AL, ACSR 25-95 ต.มม.', category: 'อุปกรณ์ยึดต่อ', quantity: 15, unit: 'ตัว', minThreshold: 8 },
  { id: '1-02-040-0002', name: 'หลอดต่อสายรับแรงดึง AL 50 ต.มม.', category: 'อุปกรณ์ยึดต่อ', quantity: 10, unit: 'ตัว', minThreshold: 5 },
  { id: '1-02-040-0019', name: 'หลอดต่อสายรับแรงดึง AL 185 ต.มม. (รหัสใหม่)', category: 'อุปกรณ์ยึดต่อ', quantity: 15, unit: 'ตัว', minThreshold: 8 },
  { id: '1-02-041-0014', name: 'หลอดต่อสายไม่รับแรงดึง AL 50 ต.มม. (รหัสใหม่)', category: 'อุปกรณ์ยึดต่อ', quantity: 10, unit: 'ตัว', minThreshold: 5 },
  { id: '1-02-041-0017', name: 'หลอดต่อสายไม่รับแรงดึง AL 185 ต.มม. (รหัสใหม่)', category: 'อุปกรณ์ยึดต่อ', quantity: 15, unit: 'ตัว', minThreshold: 8 },
  { id: '1-02-041-0102', name: 'หลอดต่อสายไม่รับแรงดึง ACSR 50 ต.มม.', category: 'อุปกรณ์ยึดต่อ', quantity: 10, unit: 'ตัว', minThreshold: 5 },
  { id: '1-02-042-0102', name: 'หางปลา AL 50 ต.มม', category: 'อุปกรณ์ยึดต่อ', quantity: 10, unit: 'ตัว', minThreshold: 5 },
  { id: '1-02-042-0104', name: 'หางปลา AL 95 ต.มม', category: 'อุปกรณ์ยึดต่อ', quantity: 6, unit: 'ตัว', minThreshold: 3 },
  { id: '1-02-042-0400', name: 'สลักต่อปลายสาย( PIN TERMINAL )', category: 'อุปกรณ์ยึดต่อ', quantity: 20, unit: 'ตัว', minThreshold: 10 },
  { id: '1-02-044-0008', name: 'CABLE SPACER,HDPE-MTEC,SAC 50-185 SQ.MM.', category: 'อุปกรณ์ยึดต่อ', quantity: 5, unit: 'ตัว', minThreshold: 3 },
  { id: '1-02-044-0119', name: 'ห่วงรัดสายเคเบิลอากาศแบบยืดหยุ่น', category: 'อุปกรณ์ยึดต่อ', quantity: 15, unit: 'ตัว', minThreshold: 8 },
  { id: '1-03-001-0101', name: 'ลูกถ้วยพินโพสท์ไทพ์ 22 เควี ชนิดทนเพาเวอร์อาร์ค', category: 'ลูกถ้วย', quantity: 6, unit: 'ลูก', minThreshold: 3 },
  { id: '1-03-002-0000', name: 'ลูกถ้วยแขวนแบบ ก (แบบ 52-1)', category: 'ลูกถ้วย', quantity: 6, unit: 'ลูก', minThreshold: 3 },
  { id: '1-03-011-0000', name: 'สเตรนแคล้มป์ ขนาด 50 ต.มม.', category: 'อุปกรณ์ยึดต่อ', quantity: 3, unit: 'ตัว', minThreshold: 2 },
  { id: '1-03-011-0004', name: 'สเตรนแคล้มป์ ขนาด 185 ต.มม.', category: 'อุปกรณ์ยึดต่อ', quantity: 3, unit: 'ตัว', minThreshold: 2 },
  { id: '1-03-014-0011', name: 'ทิมเบิ้ลเคลวิส ส่าหรับปรีฟอร์มเข้าปลายสาย', category: 'อุปกรณ์ยึดต่อ', quantity: 3, unit: 'ตัว', minThreshold: 2 },
  { id: '1-04-000-0000', name: 'ล่อฟ้าแรงสูง 20-21 เควี 5 เคเอ', category: 'อุปกรณ์ป้องกัน', quantity: 3, unit: 'ตัว', minThreshold: 2 },
  { id: '1-04-000-0007', name: 'ล่อฟ้าแรงสูง 20-21 เควี 5 เคเอ (แบบไม่มี Brackets)', category: 'อุปกรณ์ป้องกัน', quantity: 3, unit: 'ตัว', minThreshold: 1 },
  { id: '1-04-001-0002', name: 'ดรอพเอาท์ฟิวส์คัทเอาท์ หนึ่งอินซูเลเตอร์ 22 เควี 100 แอมป์ 12 เคเอ', category: 'อุปกรณ์ป้องกัน', quantity: 6, unit: 'ตัว', minThreshold: 3 },
  { id: '1-04-001-0100', name: 'ดรอพเอาท์ฟิวส์คัทเอาท์ หนึ่งอินซูเลเตอร์ 33 เควี 100 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 2, unit: 'ตัว', minThreshold: 1 },
  { id: '1-04-001-0006', name: 'กระบอกฟิวส์ 22 เควี 100 แอมป์ 12 เคเอ', category: 'อุปกรณ์ป้องกัน', quantity: 10, unit: 'ตัว', minThreshold: 5 },
  { id: '1-04-001-0102', name: 'กระบอกฟิวส์ 33 เควี 100 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 2, unit: 'ตัว', minThreshold: 1 },
  { id: '1-04-002-0011', name: 'H.R.C. FUSE, BLADE CONTACT, 50 A (รหัสใหม่)', category: 'อุปกรณ์ป้องกัน', quantity: 15, unit: 'ตัว', minThreshold: 8 },
  { id: '1-04-002-0012', name: 'H.R.C. FUSE, BLADE CONTACT, 80 A (รหัสใหม่)', category: 'อุปกรณ์ป้องกัน', quantity: 20, unit: 'ตัว', minThreshold: 10 },
  { id: '1-04-002-0013', name: 'H.R.C. FUSE, BLADE CONTACT, 100 A (รหัสใหม่)', category: 'อุปกรณ์ป้องกัน', quantity: 20, unit: 'ตัว', minThreshold: 10 },
  { id: '1-04-002-0014', name: 'H.R.C. FUSE, BLADE CONTACT, 160 A (รหัสใหม่)', category: 'อุปกรณ์ป้องกัน', quantity: 20, unit: 'ตัว', minThreshold: 10 },
  { id: '1-04-002-0015', name: 'H.R.C. FUSE, BLADE CONTACT, 200 A (รหัสใหม่)', category: 'อุปกรณ์ป้องกัน', quantity: 15, unit: 'ตัว', minThreshold: 8 },
  { id: '1-04-002-0016', name: 'H.R.C. FUSE, BLADE CONTACT, 250 A (รหัสใหม่)', category: 'อุปกรณ์ป้องกัน', quantity: 15, unit: 'ตัว', minThreshold: 8 },
  { id: '1-04-002-0017', name: 'H.R.C. FUSE, BLADE CONTACT, 315 A (รหัสใหม่)', category: 'อุปกรณ์ป้องกัน', quantity: 5, unit: 'ตัว', minThreshold: 3 },
  { id: '1-04-002-0102', name: 'FSD, FULL INSULATED, 1X400A, 400V', category: 'อุปกรณ์ป้องกัน', quantity: 15, unit: 'ตัว', minThreshold: 8 },
  { id: '1-04-003-0002', name: 'ฟิวส์แรงสูง 22 เควี ขนาด 3 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 20, unit: 'ตัว', minThreshold: 10 },
  { id: '1-04-003-0003', name: 'ฟิวส์แรงสูง 22 เควี ขนาด 6 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 20, unit: 'ตัว', minThreshold: 10 },
  { id: '1-04-003-0004', name: 'ฟิวส์แรงสูง 22 เควี ขนาด 8 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 20, unit: 'ตัว', minThreshold: 10 },
  { id: '1-04-003-0005', name: 'ฟิวส์แรงสูง 22 เควี ขนาด 10 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 20, unit: 'ตัว', minThreshold: 10 },
  { id: '1-04-003-0006', name: 'ฟิวส์แรงสูง 22 เควี ขนาด 15 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 20, unit: 'ตัว', minThreshold: 10 },
  { id: '1-04-003-0007', name: 'ฟิวส์แรงสูง 22 เควี ขนาด 20 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 20, unit: 'ตัว', minThreshold: 10 },
  { id: '1-04-003-0008', name: 'ฟิวส์แรงสูง 22 เควี ขนาด 25 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 20, unit: 'ตัว', minThreshold: 10 },
  { id: '1-04-003-0009', name: 'ฟิวส์แรงสูง 22 เควี ขนาด 30 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 10, unit: 'ตัว', minThreshold: 5 },
  { id: '1-04-003-0010', name: 'ฟิวส์แรงสูง 22 เควี ขนาด 40 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 10, unit: 'ตัว', minThreshold: 5 },
  { id: '1-04-003-0011', name: 'ฟิวส์แรงสูง 22 เควี ขนาด 50 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 10, unit: 'ตัว', minThreshold: 5 },
  { id: '1-04-003-0012', name: 'ฟิวส์แรงสูง 22 เควี ขนาด 65 แอมป์', category: 'อุปกรณ์ป้องกัน', quantity: 10, unit: 'ตัว', minThreshold: 5 },
  { id: '1-04-003-9931', name: 'Power fuse unit 22kV 100 A', category: 'อุปกรณ์ป้องกัน', quantity: 0, unit: 'ตัว', minThreshold: 0 },
  { id: '1-04-003-9932', name: 'Power fuse unit 22kV 125 A', category: 'อุปกรณ์ป้องกัน', quantity: 0, unit: 'ตัว', minThreshold: 0 },
  { id: '1-04-003-9933', name: 'Power fuse unit 22kV 150 A', category: 'อุปกรณ์ป้องกัน', quantity: 0, unit: 'ตัว', minThreshold: 0 },
  { id: '1-04-003-9934', name: 'Power fuse unit 22kV 175 A', category: 'อุปกรณ์ป้องกัน', quantity: 0, unit: 'ตัว', minThreshold: 0 },
  { id: '1-04-003-9921', name: 'HV power fuse 22kV 200A', category: 'อุปกรณ์ป้องกัน', quantity: 0, unit: 'ตัว', minThreshold: 0 },
  { id: '1-09-025-0040', name: 'DROPOUT FUSE CUTOUT COVERS', category: 'อุปกรณ์ป้องกัน', quantity: 6, unit: 'ตัว', minThreshold: 3 },
  { id: '1-03-001-0200', name: 'ลูกถ้วยแบบโพสท์ 7.5 เควี ส่าหรับสถานีเปลี่ยนแรงดัน ANSI TR-202', category: 'ลูกถ้วย', quantity: 6, unit: 'ลูก', minThreshold: 3 },
  { id: '1-04-001-0015', name: 'ANIMAL BARRIER', category: 'อุปกรณ์ป้องกัน', quantity: 6, unit: 'ตัว', minThreshold: 3 },
  { id: '1-04-001-0016', name: 'CUTOUT BRACKET', category: 'อุปกรณ์ป้องกัน', quantity: 6, unit: 'ตัว', minThreshold: 3 },
  { id: '1-09-025-0038', name: 'TRANSFORMER BUSHING COVERS', category: 'อุปกรณ์ป้องกัน', quantity: 6, unit: 'ตัว', minThreshold: 3 },
  { id: '1-09-025-0039', name: 'VOLTAGE TRANSFORMER BUSHING COVERS', category: 'อุปกรณ์ป้องกัน', quantity: 6, unit: 'ตัว', minThreshold: 3 },
  { id: '1-09-025-0041', name: 'LIGHTNING ARRESTER COVERS', category: 'อุปกรณ์ป้องกัน', quantity: 6, unit: 'ตัว', minThreshold: 3 },
  { id: '1-09-025-0037', name: 'SPLICING SLEEVE TENSIONLESS COVERS', category: 'อุปกรณ์ยึดต่อ', quantity: 6, unit: 'ตัว', minThreshold: 3 },
  { id: '1-09-025-0036', name: 'SPLICING SLEEVE TENSION COVERS', category: 'อุปกรณ์ยึดต่อ', quantity: 6, unit: 'ตัว', minThreshold: 0 },
];

export const INITIAL_VEHICLES: VehicleInventory[] = [
  { 
    vehicleId: 'V001', 
    plateNumber: 'บม 5343 ปข', 
    items: INITIAL_INVENTORY.map(item => ({
      itemId: item.id,
      quantity: item.minThreshold
    }))
  }
];

export const TOOL_LIST = [
  'ใบบริการรับการแก้ไฟฟ้าขัดข้อง (1)',
  'วิทยุสื่อสารประจำรถ VHF/UHF กำลังส่ง 10 วัตต์ (1)',
  'หมวกนิรภัย สีขาว/สีเหลือง (1)',
  'ถุงมือยางแรงต่ำพร้อมถุงหนัง (2)',
  'ถุงมือยางแรงสูงพร้อมถุงหนัง (2)',
  'ถุงมือปีนเสา (2)',
  'รองเท้านิรภัย (2)',
  'ขาปีนเสาคอนกรีต (2)',
  'เข็มขัดนิรภัยพร้อมสายกันตก (2)',
  'แว่นตานิรภัย (Safety glasses) (2)',
  'เสื้อกั๊กสะท้อนแสง (2)',
  'หน้ากากป้องกันสะเก็ด/เศษกระเด็น (1)',
  'Voltage Detector พร้อมไม้ฉนวน (1)',
  'เครื่องมือสายดิน (ชุดครบ) (1)',
  'ป้ายห้ามสับสวิตช์ (3)',
  'ป้ายเตือนอันตราย (2)',
  'กรวยยางสะท้อนแสง (10)',
  'เทปกั้นเขตการทำงาน (1)',
  'ไม้ชักฟิวส์ ชนิด 3 ท่อน หรือ 2 ท่อน (1)',
  'รอกเดี่ยวเปิดข้าง รับน้ำหนักได้ 150 กก. (ส่งของ) (1)',
  'เชือกเอนกประสงค์ (1)',
  'เครื่องมือบีบหลอดต่อสายไฮดรอลิค ขนาด 25–185 ตร.มม. (1)',
  'เครื่องมือบีบคอนเนคเตอร์แบบ H (1)',
  'คีมตัดสายไฟ AL 185 / ACSR 70–120 ตร.มม. (1)',
  'คีมตัดลวดเหล็กตีเกลียว 95 ตร.มม. (1)',
  'ค้อนปอนด์ (1)',
  'เลื่อยตัดเหล็ก (1)',
  'ประแจเลื่อน ขนาดกลาง (1)',
  'คีมล็อก (1)',
  'กล่องเก็บเครื่องมือช่างเบื้องต้นประจำรถ (1)',
  'มีดพร้า มีดงอ (1)',
  'วิทยุสื่อสารชนิดมือถือ (1)',
  'บันไดสไลด์ (1)',
  'สปอร์ทไลท์ติดรถ (2)',
  'สปอร์ทไลท์/ไฟฉายฉนิดพกพา (1)',
  'สว่าน (1)',
  'คีมรวม (2)',
  'มีดปลอกสาย'
];
